sensor:
  - platform: bme280_i2c
    pressure:
      name: "Sensor Pressure"
      id: sensor_pres
    <<: !include temperature_base.yaml
    address: 0x76
    humidity:
      name: "Sensor Humidity"
      id: sensor_hum
      filters:
        - offset: 10